export const MAX_TASK_TITLE_LENGTH = 200;
export const MAX_TASK_DESCRIPTION_LENGTH = 2000;
export const MAX_SUBTASK_TITLE_LENGTH = 200;
export const MAX_BLOCKING_REASON_LENGTH = 1000;
export const MAX_DAILY_UPDATE_CONTENT_LENGTH = 1000;
